---
title: "News"
from: markdown+emoji
---

<table>
<tr>
    <td>
**May 2025**
    </td>
    <td>
      I presented our paper ["Model-based causal feature selection for general
      response types"](https://doi.org/10.1080/01621459.2024.2395588)
      (published in the Journal of the American Statistical Association) as
      part of the [AISTATS 2025 Journal-to-Conference
      Track](https://aistats.org/aistats2025/journal-track.html).
    </td>
</tr>
<tr>
    <td>
**Aug 2024**
    </td>
    <td>
New publication :tada: ["Algorithm-agnostic significance testing in supervised
learning with multimodal data"](https://doi.org/10.1093/bib/bbae475) in
collaboration with [Anton Rask Lundborg](https://www.arlundborg.com) has been
accepted for publication in Briefings in Bioinformatics! The
corresponding `comets` R package is available on
[GitHub](https://github.com/LucasKook/comets.git) and
[CRAN](https://CRAN.R-project.org/package=comets).
    </td>
</tr>
<tr>
    <td>
**Aug 2024**
    </td>
    <td>
      New publication :tada: ["Model-based causal feature selection for general
      response types"](https://doi.org/10.1080/01621459.2024.2395588) has been
      accepted for publication in the Journal of the American Statistical
      Association. Software implementing our method is available in the R
      package `tramicp` [on GitHub](https://github.com/LucasKook/tramicp) and
      [on CRAN](https://CRAN.R-project.org/package=tramicp).
    </td>
</tr>
<tr>
    <td>
**Jun 2024**
    </td>
    <td>
New preprint :tada: ["Instrumental Variable Estimation of Distributional Causal
Effects"](https://arxiv.org/abs/2406.19986) in collaboration with [Niklas
Pfister](https://niklaspfister.github.io). Code is available on
[GitHub](https://github.com/LucasKook/dive.git).
    </td>
</tr>
<tr>
    <td>
**Apr 2024**
    </td>
    <td>
New publication :tada: ["Estimating Conditional Distributions with Neural Networks
using R package `deeptrafo`"](https://doi.org/https://doi.org/10.18637/jss.v111.i10) got
accepted for publication in the Journal of Statistical Software.
[Software](https://CRAN.R-project.org/package=deeptrafo) is available on CRAN.
    </td>
</tr>
<tr>
    <td>
**Mar 2024**
    </td>
    <td>
I started my new role as Assistant Professor of Statistics at the Institute for
      Statistics and Mathematics of the Vienna University for Economics and
      Business.
    </td>
</tr>
<tr>
    <td>
**Feb 2023**
    </td>
    <td>
I successfully defended my PhD thesis titled "Deep Learning and Causal Inference
with Transformation Models" at the University of Zurich, Switzerland.
    </td>
</tr>
<tr>
    <td>
    **Jan 2023**
    </td>
    <td>
    I acquired a postdoctoral mobility grant from the Swiss National Science
Foundation for my proposal on [Distributional Instrumental Variables Estimation
(DIVE)](https://data.snf.ch/grants/grant/214457). During the fellowship, I will
be working with [Niklas Pfister](https://niklaspfister.github.io/) and [Jonas
Peters](https://people.math.ethz.ch/~jopeters/) at the University of Copenhagen,
starting March 2023. </td>
</tr>
</table>
